config/routes.rb
      get ':page_name', action: :view
    end
  end

  resources :controller_actions do
    collection do
      get :list
      post ':id', action: :update
      get :new_for
    end
  end

  resources :course, only: %i[new create edit update] do
    collection do
      get :toggle_access
      get :copy
      get :view_teaching_assistants
      post :add_ta
      get :auto_complete_for_user_name
      post :remove_ta
    end
  end

  resources :eula, only: [] do
    collection do
      get :accept
      get :decline
      get :display
    end
  end

  resources :export_file, only: [] do
    collection do
      get :start
      get :export
      post :export
      post :exportdetails
      post :export_advices
    end
  end

  resources :grades, only: %i[edit update] do
    collection do
      get :view
      get :view_team
      get :view_reviewer
      get :view_my_scores
      get :instructor_review
      post :remove_hyperlink
      post :save_grade_and_comment_for_submission
    end
  end

  resources :impersonate, only: [] do
    collection do
      get :start
      post :impersonate
    end
  end

  resources :import_file, only: [] do
    collection do
      get :start
      get :show
      get :import
      post :show
      post :import
    end
  end

  resources :institution, except: [:destroy] do
    collection do
      get :list
      post ':id', action: :update
    end
  end

  resources :invitations, only: %i[new create] do
    collection do
      get :cancel
      get :accept
      get :decline
    end
  end

  resources :join_team_requests do
    collection do
      post :decline
    end
  end

  resources :late_policies
  resources :markup_styles

  resources :menu_items do
    collection do
      get :move_down
      get :move_up
      get :new_for
      get :link
      get :list
    end
  end

  resources :notifications

  resources :participants, only: [:destroy] do
    collection do
      get :add
      post :add
      get :auto_complete_for_user_name
      get :delete_assignment_participant
      get :list
      get :change_handle
      get :inherit
      get :bequeath_all
      get :inherit
      get :bequeath_all
      post :update_authorizations
      post :update_duties
      post :change_handle
      get :view_publishing_rights
    end
  end

  resources :password_retrieval, only: [] do
    collection do
      get :forgotten
      get :reset_password
      post :send_password
      post :update_password
    end
  end

  resources :profile, only: %i[edit update]

  resources :publishing, only: [] do
    collection do
      get :view
      post :update_publish_permissions
      post :set_publish_permission
      get :grant
      get :grant_with_private_key
      post :grant_with_private_key
      get :set_publish_permission
    end
  end

  resources :questionnaires, only: %i[new create edit update] do
    collection do
      get :copy
      get :new_quiz
      get :select_questionnaire_type
      post :select_questionnaire_type
      get :toggle_access
      get :view
      post :create_quiz_questionnaire
      post :update_quiz
      post :add_new_questions
      post :save_all_questions
    end
  end

  resources :author_feedback_questionnaires, controller: :questionnaires
  resources :review_questionnaires, controller: :questionnaires
  resources :metareview_questionnaires, controller: :questionnaires
  resources :teammate_review_questionnaires, controller: :questionnaires
  resources :survey_questionnaires, controller: :questionnaires
  resources :assignment_survey_questionnaires, controller: :questionnaires
  resources :global_survey_questionnaires, controller: :questionnaires
  resources :course_survey_questionnaires, controller: :questionnaires
  resources :bookmark_rating_questionnaires, controller: :questionnaires

  resources :questions do
    collection do
      get :types
    end
  end

  resources :reports, only: [] do
    collection do
      post :response_report
      get :response_report
    end
  end

  resources :reputation_web_service, only: [] do
    collection do
      get :client
      post :send_post_request
    end
  end

  resources :response, only: %i[new create edit update] do
    collection do
      get :new_feedback
      get :view
      get :remove_hyperlink
      get :save
      get :redirect
      get :show_calibration_results_for_student
      post :custom_create
      get :pending_surveys
      get :json
      get :analysis
      post :confirm_submit
    end
  end

  resources :review_mapping, only: [] do
    collection do
      post :add_metareviewer
      get :add_reviewer
      post :add_reviewer
      post :add_self_reviewer
      get :add_self_reviewer
      get :add_user_to_assignment
      get :auto_complete_for_user_name
      get :delete_all_metareviewers
      get :delete_outstanding_reviewers
      get :delete_metareviewer
      get :delete_reviewer
      get :distribution
      get :list_mappings
      # post :response_report
      # get :response_report
      get :select_metareviewer
      get :select_reviewer
      get :select_mapping
      post :assign_quiz_dynamically
      get :assign_reviewer_dynamically
      post :assign_reviewer_dynamically
      get :assign_metareviewer_dynamically
      post :assign_metareviewer_dynamically
      post :automatic_review_mapping
      post :automatic_review_mapping_staggered
      # E1600
      post :start_self_review
      post :save_grade_and_comment_for_reviewer
      get :unsubmit_review
    end
  end

  resources :roles do
    collection do
      get :list
      post ':id', action: :update
    end
  end

  resources :sign_up_sheet, except: %i[index show] do
    collection do
      get :signup
      get :delete_signup
      get :add_signup_topics
      get :add_signup_topics_staggered
      get :delete_signup
      get :list
      get :signup_topics
      get :signup
      get :sign_up
      get :team_details
      get :intelligent_sign_up
      get :intelligent_save
      get :signup_as_instructor
      post :delete_all_topics_for_assignment
      post :signup_as_instructor_action
      post :set_priority
      post :save_topic_deadlines
    end
  end

  resources :site_controllers do
    collection do
      get :list
      get :new_called
    end
  end

  resources :student_quizzes, only: [:index] do
    collection do
      post :student_quizzes
      post :record_response
      get :finished_quiz
      get :take_quiz
      get :review_questions
    end
  end

  resources :student_review, only: [] do
    collection do
      get :list
    end
  end

  resources :student_task, only: [] do
    collection do
      get :list
      get :view
      put :make_public
      get '/*other', to: redirect('/student_task/list')
    end
  end

  resources :student_teams, only: %i[create edit update] do
    collection do
      get :view
      get :remove_participant
      get :auto_complete_for_user_name
    end
  end

  resources :submitted_content, only: [:edit] do
    collection do
      get :download
      get :folder_action
      get :remove_hyperlink
      post :remove_hyperlink
      get :submit_file
      post :submit_file
      post :folder_action
      post :submit_hyperlink
      get :submit_hyperlink
      get :view
    end
  end

  resources :submission_records, only: [:index]

  resources :suggestion, only: %i[show new create] do
    collection do
      get :list
      post :submit
      post :student_submit
      post :update_suggestion
    end
  end

  resources :survey_deployment, only: %i[new create] do
    collection do
      get :list
      get :reminder_thread
    end
  end

  resources :system_settings do
    collection do
      get :list
    end
  end

  resources :teams, only: %i[new create edit update] do
    collection do
      get :list
      # post ':id', action: :create_teams
      post :create_teams
      post :inherit
    end
  end

  resources :teams_users, only: %i[new create] do
    collection do
      post :list
    end
  end

  resources :tag_prompts, except: %i[new edit]
  resources :track_notifications, only: [:index]

  resources :tree_display, only: [] do
    collection do
      get :action
      post :list
      post :children_node_ng
      post :children_node_2_ng
      post :bridge_to_is_available
      get :session_last_open_tab
      get :set_session_last_open_tab
    end
  end

  resources :users, constraints: {id: /\d+/} do
    collection do
      get :list
      post :list
      get :list_pending_requested
      post ':id', action: :update
      get :show_selection
      get :auto_complete_for_user_name
      get :set_anonymized_view
      get :keys
      post :create_requested_user_record
      post :create_approved_user
    end
  end

  resources :user_pastebins

  resources :versions, only: %i[index show] do
    collection do
      get :search
    end
  end

  root to: 'content_pages#view', page_name: 'home'
  post :login, to: 'auth#login'
  post :logout, to: 'auth#logout'
  get 'auth/:provider/callback', to: 'auth#google_login'
  get 'auth/failure', to: 'content_pages#view'
  get '/auth/*path', to: redirect('/')
  get '/menu/*name', controller: :menu_items, action: :link
  get ':page_name', controller: :content_pages, action: :view, method: :get
  post 'impersonate/impersonate', to: 'impersonate#impersonate'
  post '/plagiarism_checker_results/:id' => 'plagiarism_checker_comparison#save_results'
  get 'instructions/home'
  get 'response/', to: 'response#saving'
  get ':controller/service.wsdl', action: 'wsdl'
  get 'password_edit/check_reset_url', controller: :password_retrieval, action: :check_reset_url
  get ':controller(/:action(/:id))(.:format)'
  match '*path' => 'content_pages#view', :via => %i[get post] unless Rails.env.development?
  put 'student_task/make_public', controller: :student_task,  action: :make_public, method: :put
  post '/suggestion/update_visibility/', to: 'suggestion#update_visibility'

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  autocomplete :user, :name
  require 'gchart'
  helper :submitted_content
  include ReportFormatterHelper

  # reports are allowed to be viewed by  only by TA, instructor and administrator
  def action_allowed?
    ['Instructor', 'Teaching Assistant', 'Administrator'].include? current_role_name
  end

  def response_report
    # ACS Removed the if condition(and corresponding else) which differentiate assignments as team and individual assignments
    # to treat all assignments as team assignments
    @type = params.key?(:report) ? params[:report][:type] : 'basic'
    # From the ReportFormatterHelper module
    send(@type.underscore, params, session)
    @user_pastebins = UserPastebin.get_current_user_pastebin current_user
  end
end

app/views/reports/_feedback_report.html.erb
<%= create_report_table_header("Rejoinder" => "16%",
                               "# author feedbacks done" => "14%",
                               "Review response rejoined" => "20%",
                               "Last rejoined at" => "20%") %>
    <%@l = -1 %>

    <% @authors.each do |r| %>
      <% next unless r %>
      <% if @assignment.varying_rubrics_by_round? %>
        <% get_each_review_and_feedback_response_map(r) %>
      <% else %>
        <% get_certain_review_and_feedback_response_map(r) %>
      <% end %>

      <% @first_col_identifier = true %>
      <% if @assignment.varying_rubrics_by_round? %>
          <!--data prepare-->
          <% @count_round_one, @count_round_two, @count_round_three = 0, 0, 0 %>
          <% unless @feedback_response_maps_round_one.nil? %>
            <% @feedback_response_maps_round_one.each  do |rm| %>
              <% if Response.exists? map_id: rm.id %>
                <% @count_round_one += 1%>
              <% end %>
            <% end %>
          <% end %>
          <% unless @feedback_response_maps_round_two.nil? %>
            <% @feedback_response_maps_round_two.each {|rm| @count_round_two += 1 if Response.exists? map_id: rm.id} %>
          <% end %>
          <% unless @feedback_response_maps_round_three.nil? %>
            <% @feedback_response_maps_round_three.each {|rm| @count_round_three += 1 if Response.exists? map_id: rm.id} %>
          <% end %>

          <!--Rejoinder-->
        <% ['one', 'two', 'three'].each do |round| %>
          <% if @first_col_identifier == true %>
            <% @reviewer_name = r.user.fullname(session[:ip]) %>
            <tr><td rowspan= <%= @assignment.varying_rubrics_by_round? ? (@rspan_round_one + @rspan_round_two + @rspan_round_three) : @rspan %>>
              <%= link_to @reviewer_name, :controller => 'popup', :action => 'reviewer_details_popup', :id => r.id, :assignment_id => @id %>
            </td>
            <% @first_col_identifier = false %>
          <% end %>

          <!--# author feedbacks done-->
          <% @rspan_certain_round = instance_variable_get("@rspan_round_#{round}") %>
          <% @count_certain_round = instance_variable_get("@count_round_#{round}") %>
          <% unless @rspan_certain_round == 0 %>
            <% @l = @l+1 %>
            <% (@l % 2 == 0) ? @bgcolor = "#ffffff" : @bgcolor = "#f9f9f9" %>
            <td bgcolor=<%= @bgcolor %>  align="left" rowspan= <%= @rspan_certain_round %>>
              <%= @count_certain_round %>/<%= @rspan_certain_round %></td>
          <% end %>

          <% @review_responses_certain_round = instance_variable_get("@review_responses_round_#{round}") %>
          <% @review_responses_certain_round.each do |rr| %>
            <!--'FeedbackResponseMap' alias as 'frm' -->
            <% @frm = FeedbackResponseMap.where(["reviewed_object_id = ? and reviewer_id = ? and reviewee_id = ?", rr.id, r.id, rr.response_map.reviewer_id]).first %>

            <% if @frm.blank? %>
              <!--Review response rejoined-->
              <td id = "green" bgcolor=<%= @bgcolor %> style="color:#A90201" align = 'left' colspan=1>
                <%= link_to user_name = Participant.find(rr.response_map.reviewer_id).user.name(session[:ip]), impersonate_impersonate_path(:user => {:name => user_name}), :method => :post, :title => "Click here to impersonate this user" %>
                (<%= Participant.find(rr.response_map.reviewer_id).user.fullname(session[:ip]) %>)
              </td>
              <!--Last rejoined at-->
              <td bgcolor=<%= @bgcolor %> style="color:#A90201" align = 'left'>No</td></tr><tr>
            <% else %>
              <% @reviewee_name = Participant.find(@frm.reviewee_id).user.fullname(session[:ip]) %>
              <% if Response.exists?(map_id: @frm.id) %>
                <% feedback_response = Response.where(map_id: @frm.id).first %>
                <!--Review response rejoined-->
                <td id = "green" bgcolor=<%= @bgcolor %> align='left' colspan=1>
                  <%= link_to user_name = Participant.find(rr.response_map.reviewer_id).user.name(session[:ip]), impersonate_impersonate_path(:user => {:name => user_name}), :method => :post, :title => "Click here to impersonate this user" %>
                  (<%= link_to @reviewee_name, :controller => 'popup', :action => 'author_feedback_popup', :response_id => feedback_response.id, :reviewee_id => @frm.reviewee_id, :source => 'author_feedback' %>)
                </td>
                <!--Last rejoined at-->
                <td bgcolor=<%= @bgcolor %> align='left'>
                  <%= feedback_response.updated_at.to_time.strftime("%m/%d/%Y - %I:%M%p") %>
                </td></tr><tr>
              <% else %>
                <!--Review response rejoined-->
                <td id = "green" bgcolor=<%= @bgcolor %> style="color:#A90201" align = 'left' colspan=1>
                  <%= link_to user_name = Participant.find(rr.response_map.reviewer_id).user.name(session[:ip]), impersonate_impersonate_path(:user => {:name => user_name}), :method => :post, :title => "Click here to impersonate this user" %>
                  (<%= @reviewee_name %>)
                </td>
                <!--Last rejoined at-->
                <td bgcolor=<%= @bgcolor %> style="color:#A90201" align = 'left'>No</td></tr><tr>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
          <% @count = 0 %>
          <% @feedback_response_maps.each {|rm| @count += 1 if Response.exists? map_id: rm.id} %>
          <% @l = @l+1 %>
          <% (@l % 2 == 0) ? @bgcolor = "#ffffff" : @bgcolor = "#f9f9f9" %>
          <!--Rejoinder-->
          <tr><td bgcolor=<%= @bgcolor %> rowspan= <%= @assignment.varying_rubrics_by_round? ? (@rspan_round_one + @rspan_round_two + @rspan_round_three) : @rspan %>>
            <% @reviewer_name = r.user.fullname(session[:ip]) %>
            <%= link_to @reviewer_name, :controller => 'popup', :action => 'reviewer_details_popup', :id => r.id, :assignment_id => @id %>
          </td>

          <!--# author feedbacks done-->
          <% unless @rspan == 0 %>
            <td bgcolor=<%= @bgcolor %>  align="left" rowspan= <%= @rspan %>>
              <%= @count %>/<%= @rspan %>
            </td>
          <% end %>
          <% @review_responses.each do |rr| %>
            <!--'FeedbackResponseMap' alias as 'frm' -->
            <% @frm = FeedbackResponseMap.where(["reviewed_object_id = ? and reviewer_id = ? and reviewee_id = ?", rr.id, r.id, rr.response_map.reviewer_id]).first %>

            <% if @frm.blank? %>
              <!--Review response rejoined-->
              <td id = "green" bgcolor=<%= @bgcolor %> style="color:#A90201" align = 'left' colspan=1>
                <%= link_to user_name = Participant.find(rr.response_map.reviewer_id).user.name(session[:ip]), impersonate_impersonate_path(:user => {:name => user_name}), :method => :post, :title => "Click here to impersonate this user" %>
                (<%= reviewee_name = Participant.find(rr.response_map.reviewer_id).user.fullname(session[:ip]) %>)
              </td>
              <!--Last rejoined at-->
              <td bgcolor=<%= @bgcolor %> style="color:#A90201" align = 'left'>No</td></tr><tr>
            <% else %>
              <% @reviewee_name = Participant.find(@frm.reviewee_id).user.fullname(session[:ip]) %>
              <% if Response.exists?(map_id: @frm.id) %>
                <% feedback_response = Response.where(map_id: @frm.id).last %>
                <!--Review response rejoined-->
                <td id = "green" bgcolor=<%= @bgcolor %> align='left' colspan=1>
                  <%= link_to user_name = Participant.find(rr.response_map.reviewer_id).user.name(session[:ip]), impersonate_impersonate_path(:user => {:name => user_name}), :method => :post, :title => "Click here to impersonate this user"%>
                  (<%= link_to @reviewee_name, :controller => 'popup', :action => 'author_feedback_popup', :response_id => feedback_response.id, :reviewee_id => @frm.reviewee_id, :source => 'author_feedback' %>)
                </td>
                <!--Last rejoined at-->
                <td bgcolor=<%= @bgcolor %> align='left'>
                  <%= feedback_response.updated_at.to_time.strftime("%m/%d/%Y - %I:%M%p") %>
                </td></tr><tr>
              <% else %>
                <!--Review response rejoined-->
                <td id = "green" bgcolor=<%= @bgcolor %> style="color:#A90201" align = 'left' colspan=1>
                  <%= link_to user_name = Participant.find(rr.response_map.reviewer_id).user.name(session[:ip]), impersonate_impersonate_path(:user => {:name => user_name}), :method => :post, :title => "Click here to impersonate this user" %>
                  (<%= @reviewee_name %>)
                </td>
                <!--Last rejoined at-->
                <td bgcolor=<%= @bgcolor %> style="color:#A90201" align = 'left'>No</td></tr><tr>
              <% end %>
            <% end %>
          <% end %>
      <% end %>
    <% end %>
  </table>
</div>

app/views/reports/_review_report.html.erb
<!-- the table creation is changed top accommodate functionality of tablesorter, which requires thead and tbody seperately. Previously, headers were in tbody only -->
<div class='reviewreport'>
  <!-- Added headers for tablesorter -->

  <script type='text/javascript'>
      $(window).load(function () {
          $("#myTable tbody").sortable().disableSelection();
          $("#dialog").dialog({
            autoOpen: false,
            modal: true,
            show: "blind",
            hide: "blind",
            buttons: {
              Ok: function() {
                $(this).dialog("close");
              }
            }
          });
      });
  </script>

  <div id="dialog" title="Success">Grade and comment for reviewer successfully saved.</div>

  <p> **In "Team reviewed" column text in:</p>
    <ul style="list-style-type:square">
  <li><i style="color:red">red</i> indicates that the review is not  completed in any rounds;</li>
  <li><i style="color:blue">blue</i> indicates that a review is completed in every round and the review grade is not assigned;</li>
  <li><i style="color:green">green</i> indicates that there is no submitted work to review within the round;</li>
  <li><i style="color:purple">purple</i> indicates that there is no review for a submitted work within the round;</li>
  <li><i style="color: #986633">brown</i> indicates that the review grade has been assigned</li>
</ul>
  <p>&nbsp;</p>
  
  <table id="myTable" class="tbl_heat tablesorter" width="100%" cellspacing='0' cellpadding='2' border='0'>
    <thead>
    <tr bgcolor='#CCCCCC'>
      <!-- class value decides whether the column should be sortable or not  -->
      <th width="16%" class="sorter-true">Reviewer <span></span></th>
      <th width="10%" class="sorter-false">Reviews done<span></span></th>
      <th width="24%" class="sorter-false">Team reviewed <span></span></th>
      <th width="13%" class="sorter-false">Score awarded / Avg. score <span></span></th>
      <th width="13%" class="sorter-true">Metrics <span></span></th>
      <th class="sorter-false">Assign grade and write comments <span></span></th>
    </tr>
    </thead>
    <tbody>

    <% sort_reviewer_by_review_volume_desc.each do |r| %>
      <% @response_maps, @rspan = get_data_for_review_report(@id, r.id, @type) %>
      <tr>
        <% if r.id != -1 %>
          <% user = Participant.find(r.id).user %>
            <!--reviewer-->
            <td>
              <%= link_to user.name(session[:ip]), impersonate_impersonate_path(:user => {:name => user.name(session[:ip])}), :method => :post %>
              (<%= user.fullname(session[:ip]) %>)
            </td>
            <!--# reviews done-->
            <td align = 'left'>
              <% (1..@assignment.num_review_rounds).each do |round| %>
                <%= instance_variable_get("@review_in_round_" + round.to_s) %>/<%= @rspan %>
                <%= ', ' unless round == @assignment.num_review_rounds %>
              <% end %>
              <%= link_to "summary", {:controller => 'popup', :action => 'view_review_scores_popup', :reviewer_id => r.id, :assignment_id=>@id}, target: :_blank %>
            </td>
          <!--Team reviewed / Author feedback-->
          <td align = 'left'>
          <% @response_maps.each_with_index do |ri, index| %>
            <!--For assignments with team member 1, team reviewed column should show username instead of team name, which is randomly generated.-->
            <% team_name_color = get_team_colour(ri) %>
            <% team_reviewed_link_name = get_team_reviewed_link_name(@assignment.max_team_size, ri.response, ri.reviewee_id) %>
              <% if Team.where(id: ri.reviewee_id).length > 0 %>
                <!--Team reviewed-->
                <% if index == 0 %>
                  <div id= <%= team_name_color %>>
                <% else %>
                  <div id = <%= team_name_color %> style="border-top:solid;border-width:1px;">
                <% end %>
                    <%= link_to team_reviewed_link_name, :controller => 'popup', :action => 'team_users_popup', :id => ri.reviewee_id, :id2 => ri.id, :assignment_id=>@id %>
                    <%= list_review_submissions(r.id, ri.reviewee_id, ri.id) %>
                    <!--Hard-coded Dr.Kidd's question in order to display link.-->
                    <!--later we can create a hyperlink question type to deal with this situation.-->
                    <%= list_hyperlink_submission(ri.id, 5386) if Assignment.find_by(id: @id.to_i).course.instructor.name == 'Jkidd' %>
                    <div style="display: inline; float: right; font-size: 10px"><%= "done at - " + ri.response.last.updated_at.strftime("%a, %b %d, %Y %I:%M:%S %p") if ri.response and ri.response.last %>&nbsp&nbsp&nbsp</div>
                  </div>

                <!--Author feedback-->
                <!--Dr.Kidd required to add a "author feedback" column that shows the average score the reviewers received from the authors. In this case, she can see all the data on a single screen.-->
                <!--Dr.Kidd's course-->
                <!--
                <% if @assignment.instructor_id == 2026 %>
                  <% if index == 0 %>
                  <div>
                  <% else %>
                  <div style="border-top: solid; border-width: 1px;">
                  <% end %>
                    <%= calcutate_average_author_feedback_score(@assignment.id, @assignment.max_team_size, ri.id, ri.reviewee_id) %>
                  </div>
                <% end %>-->
              <% end %>
            <% end %>
          </td>
          <!--Score awarded / Avg. score-->
          <td align='left'>
            <% @response_maps.each_with_index do |ri, index| %>
              <% if Team.where(id: ri.reviewee_id).length > 0 %>
                <% @team = Team.find(ri.reviewee_id) %>
                <%= render partial: 'team_score', locals: {bgcolor: @bgcolor, team_id: @team.id, reviewer_id: r.id} %>
              <% end %>
            <% end %>
          </td>
          <!--Metrics-->
          <td align='left'>
            <%= display_volume_metric_chart(r) %>
            <%= display_review_metrics_chart(r) %>
          </td>
          <!--Assign grade and write comments-->
          <td align='left'>
            <%= form_tag save_grade_and_comment_for_reviewer_review_mapping_index_path, remote: true do %>
              <%= hidden_field_tag :participant_id, r.id %>
              <%= hidden_field_tag :assignment_id, @id %>
              <%= number_field_tag 'grade_for_reviewer', r.review_grade.try(:grade_for_reviewer), min: 0, max: 100, maxlength: 3, size: 3, placeholder: 'Grade' %>
              <br/>
              <%= text_area_tag 'comment_for_reviewer', r.review_grade.try(:comment_for_reviewer), placeholder: 'Comment', class: "awesome_input", 'data-multiple' => '', 'data-minchars' => "1" %>
              <table class="inline-transparent">
                <tr>
                  <td>
                    <%= image_tag 'text_macro.png', :border => 2, :title => 'Text Macro/Pastebin', :style => 'width: 24px; height:30px', :onclick => 'show_text_macros()' %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <%= submit_tag 'Save' %>
                  </td>
                </tr>
              </table>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </table>
 </div>
<!--Partial for text macro form-->
<%= render :partial => '/user_pastebins/save_text_macros' %>

<script>
    $(function () {
        /*Function for sorting the table */
        $("#myTable").tablesorter({
            sortList: [[0, 0]], //sort First Column by default when page loads
            widgets: ['zebra'], // Make sure to update the css when column is sorted
            headers: {
                4: {
                    sorter: 'customParser' //custom Parser to parse Metrics data for the custom parser
                }
            }
        });
    });


    $.tablesorter.addParser({
        id: "customParser",                                       //customParser for sorting by volume
        is: function (stringValue) {
            return false;
        },
        format: function (stringValue) {
            var stringNumericPart = stringValue.split(" ");         //split the data by spaces
            var numericValue = parseInt(stringNumericPart[2], 10);   //extract the numeric data
            return numericValue;
        },
        type: 'numeric'
    });
</script>

app/views/reports/_self_review_report.html.erb
<%= create_report_table_header("Reviewer" => "16%",
                               "Self review" => "20%",
                               "Last reviewed at" => "20%") %>
    <%@l = -1 %>
    <% @self_review_response_maps.each do |sr| %>
      <%@l = @l+1 %>
      <% (@l % 2 == 0) ? @bgcolor = "#ffffff" : @bgcolor = "#DDDDBB" %>
      <!--Reviewer-->
      <td id = "green" bgcolor=<%= @bgcolor %> align='left'>
        <%= link_to @user_name = Participant.find(sr.reviewer_id).user.name(session[:ip]), impersonate_impersonate_path(:user => {:name => @user_name}), :method => :post, :title => "Click here to impersonate this user" %>
      </td>
      <!--Self review-->
      <td id = "green" bgcolor=<%= @bgcolor %> align='left'>
        <% if sr.response.first %>
          <%= link_to @user_name, controller: 'popup', action: 'self_review_popup', response_id: sr.response.first.id, user_fullname: Participant.find(sr.reviewer_id).user.fullname(session[:ip]) %>
        <% else %>
          <%= @user_name %>
        <% end %> 
      </td>
      <!--Last reviewed at-->
      <td bgcolor=<%= @bgcolor %> align='left'>
        <%= sr.updated_at.to_time.strftime("%m/%d/%Y - %I:%M%p") %>
      </td></tr><tr>
    <% end %>
  </table>
</div>